[package]
name = "kakuro"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13"
crossterm = "0.28" 
rand = "0.8" 
board = "0.2.2"
cell = "0.1.8"
io = "0.0.2"
assert_cmd = "2.1.1"
predicates = "3.1.3"
enigo = "0.6.1"
ntest = "0.9.3"
pseudoterminal = "0.2.1"
